### ISSUE TITLE
Python2 version errors out during install.

### ISSUE THREAD

**Issue by BlackestDawn** [kurtmckee/feedparser#104]
I'm using a virtualenv that has both version 2.7 and 3.4 in it. Trying to install Feedparser (or pulling it as a dependency) under 2.7 makes it error out but under 3.4 it works just fine.
Feedparser version: 5.2.1

`Exception:
Traceback (most recent call last):
  File "/home/blacke/py-envs/flexget/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/blacke/py-envs/flexget/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/blacke/py-envs/flexget/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/blacke/py-envs/flexget/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/blacke/py-envs/flexget/lib/python2.7/site-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/home/blacke/py-envs/flexget/lib/python2.7/site-packages/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/usr/lib64/python2.7/email/feedparser.py", line 177, in feed
    self._input.push(data)
  File "/usr/lib64/python2.7/email/feedparser.py", line 99, in push
    parts = data.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'`

**Comment by kurtmckee** [comment]
feedparser 6.0.0 has been released and drops Python 2 support. Closing.
