### ISSUE TITLE
Download error...

### ISSUE THREAD

**Issue by petasis** [kurtmckee/feedparser#146]
Hi all,

I am facing trouble downloading some feed urls, like:

https://meaculpa.gr/politiki?format=feed

The error I get is:

Traceback (most recent call last):
  File "find_feed.py", line 26, in <module>
    print(is_feed('https://meaculpa.gr/politiki?format=feed'))
  File "find_feed.py", line 9, in is_feed
    d = feedparser.parse(url)
  File "/home/petasis/.local/lib/python3.6/site-packages/feedparser.py", line 3866, in parse
    data = gzip.GzipFile(fileobj=_StringIO(data)).read()
  File "/usr/lib64/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.6/gzip.py", line 454, in read
    self._read_eof()
  File "/usr/lib64/python3.6/gzip.py", line 498, in _read_eof
    crc32, isize = struct.unpack("<II", self._read_exact(8))
  File "/usr/lib64/python3.6/gzip.py", line 400, in _read_exact
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

I am using Python 3.6.6.

**Comment by noMICROSOFTbuhtz** [comment]
I can not reproduce your errors. Please provide some **minimal working code** to reproduce your problem.

This is what I did
```
>>> url = 'https://meaculpa.gr/politiki?format=feed'
>>> a = fp.parse(url)
>>> a.status
200
>>> len(a.entries)
22
>>> a.bozo
0
>>> 

```
