### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by medecau** [kurtmckee/feedparser#213]
tox fails to build the package for testing.

I have tried calling tox directly AND inside a new virtualenv with sgmllib3k installed. Same results on both.
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0c/zjp95vcd0ng3_3mpytdt70jc0000gn/T/pip-req-build-uxo5h231/setup.py", line 33, in <module>
        import feedparser
      File "/private/var/folders/0c/zjp95vcd0ng3_3mpytdt70jc0000gn/T/pip-req-build-uxo5h231/feedparser/__init__.py", line 31, in <module>
        from .api import parse
      File "/private/var/folders/0c/zjp95vcd0ng3_3mpytdt70jc0000gn/T/pip-req-build-uxo5h231/feedparser/api.py", line 55, in <module>
        from .html import _BaseHTMLProcessor
      File "/private/var/folders/0c/zjp95vcd0ng3_3mpytdt70jc0000gn/T/pip-req-build-uxo5h231/feedparser/html.py", line 40, in <module>
        from .sgml import *
    AttributeError: module 'feedparser.sgml' has no attribute 'charref'
``

**Comment by shmokmt** [comment]
I am facing the same problem

**Comment by kurtmckee** [comment]
This is happening because sgmllib3k isn't getting installed by tox. I'm investigating now.
