### ISSUE TITLE
Can no longer parse PSF (PythonSoftwareFoundation) feed

### ISSUE THREAD

**Issue by impredicative** [kurtmckee/feedparser#217]
This used to work until last week, and now it doesn't:

```python-traceback
>>> feedparser.__version__
'5.2.1'

>>> feedparser.parse('https://feeds.feedburner.com/PythonSoftwareFoundationNews')
Traceback (most recent call last):
  File "/home/homeuser/PycharmProjects/.venv/myproj/lib/python3.8/site-packages/feedparser.py", line 3766, in _gen_georss_coords
    t = [nxt(), nxt()][::swap and -1 or 1]
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/homeuser/PycharmProjects/.venv/myproj/lib/python3.8/site-packages/feedparser.py", line 3956, in parse
    saxparser.parse(source)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 461, in EndElement
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/homeuser/PycharmProjects/.venv/myproj/lib/python3.8/site-packages/feedparser.py", line 2052, in endElementNS
    self.unknown_endtag(localname)
  File "/home/homeuser/PycharmProjects/.venv/myproj/lib/python3.8/site-packages/feedparser.py", line 696, in unknown_endtag
    method()
  File "/home/homeuser/PycharmProjects/.venv/myproj/lib/python3.8/site-packages/feedparser.py", line 1463, in _end_georss_point
    geometry = _parse_georss_point(self.pop('geometry'))
  File "/home/homeuser/PycharmProjects/.venv/myproj/lib/python3.8/site-packages/feedparser.py", line 3775, in _parse_georss_point
    coords = list(_gen_georss_coords(value, swap, dims))
RuntimeError: generator raised StopIteration
```

**Comment by impredicative** [comment]
This issue doesn't exist with `feedparser==6.0.0b3`.
