### ISSUE TITLE
errors in currently released version?

### ISSUE THREAD

**Issue by hennar** [kurtmckee/feedparser#230]
Installed feedparser using: pip3 install feedparser

Subsequently I'm getting these errors:
Traceback (most recent call last):
  File "fetch_rss.py", line 1, in <module>
    import feedparser
  File "/usr/local/lib/python3.5/dist-packages/feedparser/__init__.py", line 31, in <module>
    from .api import parse
  File "/usr/local/lib/python3.5/dist-packages/feedparser/api.py", line 56, in <module>
    from . import http
  File "/usr/local/lib/python3.5/dist-packages/feedparser/http.py", line 156
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'

Nothing else changed

**Comment by kurtmckee** [comment]
Python 3.5 is not supported in feedparser 6.0.0. It goes end-of-life at the end of this month so I excluded it from support.

Please try using Python 3.6 or higher.

**Comment by kurtmckee** [comment]
I've released 6.0.1 with a *python_requires* line that should prevent installing older Python versions from picking up the latest version.
