### ISSUE TITLE
tests fail with "feedparser.exceptions.UndeclaredNamespace: 'itunes' is not associated with a namespace"

### ISSUE THREAD

**Issue by heirecka** [kurtmckee/feedparser#236]
With feedparser 6.0.1:

```
python3.8 -B -Wd tests/runtests.py
..........E.....Invalid argument..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
ERROR: test_001966 (__main__.TestCase)
./tests/illformed/undeclared_namespace.xml: undeclared namespace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/runtests.py", line 872, in fn
    self.fail_unless_eval(xmlfile, eval_string)
  File "tests/runtests.py", line 171, in fail_unless_eval
    env = feedparser.parse(xmlfile)
  File "/var/tmp/paludis/build/dev-python-feedparser-6.0.1/work/PYTHON_ABIS/3.8/feedparser-6.0.1/build/lib/feedparser/api.py", line 255, in parse
    saxparser.parse(source)
  File "/usr/lib/python3.8/site-packages/drv_libxml2.py", line 215, in parse
    self._cont_handler.startElementNS( \
  File "/var/tmp/paludis/build/dev-python-feedparser-6.0.1/work/PYTHON_ABIS/3.8/feedparser-6.0.1/build/lib/feedparser/parsers/strict.py", line 70, in startElementNS
    raise UndeclaredNamespace("'%s' is not associated with a namespace" % givenprefix)
feedparser.exceptions.UndeclaredNamespace: 'itunes' is not associated with a namespace

----------------------------------------------------------------------
Ran 4334 tests in 3.228s

FAILED (errors=1)
```

**Comment by fazalmajid** [comment]
Also the case in 6.0.2, e.g. with https://greenwald.substack.com/feed/

**Comment by kurtmckee** [comment]
This appears to be related to the libxml2 `drv_libxml2.py` code.

```
File "/usr/lib/python3.8/site-packages/drv_libxml2.py", line 215, in parse
```

I'm not able to recreate this on Windows yet. If you work from a virtual environment and do not install `drv_libxml2.py` does this still occur?

**Comment by fazalmajid** [comment]
No, in a virtualenv with just `feedparser` installed using `pip`, with Python 3.9, it doesn't throw the exception. On the same machine, with drv_libxml2 installed in the system Python 3.9, it does raise the exception.
