### ISSUE TITLE
Example "Accessing multiple categories" in the documentation fails

### ISSUE THREAD

**Issue by thomasmoor** [kurtmckee/feedparser#293]
Hi,

It looks like there has been a change on "multiple categories". 

The example "Accessing multiple categories" in the documentation (https://feedparser.readthedocs.io/en/latest/uncommon-rss.html) does not work.

Here is the result of my test:

>>> import feedparser
>>> d = feedparser.parse('http://feedparser.org/docs/examples/rss20.xml')
>>> d.feed.categories
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\feedparser\util.py", line 156, in __getattr__
    return self.__getitem__(key)
  File "C:\Python3\lib\site-packages\feedparser\util.py", line 113, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'categories'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3\lib\site-packages\feedparser\util.py", line 158, in __getattr__
    raise AttributeError("object has no attribute '%s'" % key)
AttributeError: object has no attribute 'categories'
>>>

I just installed feedparser. I am on version 6.0.8

Categories are important for me
Thanks

**Comment by n3s7or** [comment]
It seems the domain name expired ??, well when you hit that link it doesn't contain the expected `xml` example, so the parsed feed is whatever is hosted there and fails.

**Comment by kurtmckee** [comment]
This should be fixed now.
