### ISSUE TITLE
'str' does not support the buffer interface

### ISSUE THREAD

**Issue by vinegret** [kurtmckee/feedparser#30]
I create simple example:
```python
#!/usr/bin/python3

import feedparser

d = feedparser.parse('http://planet.gnu.org/atom.xml')
print(d['feed']['title'])
```

I get the following:
```
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    d = feedparser.parse('http://planet.gnu.org/atom.xml')
  File "/usr/lib64/python3.4/site-packages/feedparser-5.2.1-py3.4.egg/feedparser/api.py", line 235, in parse
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 189, in parse
    eltName = (_d(reader.NamespaceUri()),\
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 70, in _d
    return _decoder(s)[0]
  File "/usr/lib64/python3.4/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'str' does not support the buffer interface
```
When using python2 this problem don't occur.
*feedparser 5.2.1*

**Comment by CthulhUzzz** [comment]
I have the same error with  lxml driver
feedparser 5.2.1
python 3.4.3

**Comment by trb143** [comment]
Just started to happen when upgrading machine from fedora 22 to fedora 23.

**Comment by potuz** [comment]
Same problem as the OP here on different versions:
$ cat exameple.py
#!/usr/bin/python3

import feedparser

d = feedparser.parse('http://planet.gnu.org/atom.xml')
print(d['feed']['title'])
$ python exameple.py 
Traceback (most recent call last):
  File "exameple.py", line 5, in <module>
    d = feedparser.parse('http://planet.gnu.org/atom.xml')
  File "/usr/lib64/python3.4/site-packages/feedparser.py", line 3991, in parse
    saxparser.parse(source)
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 189, in parse
    eltName = (_d(reader.NamespaceUri()),\
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 70, in _d
    return _decoder(s)[0]
  File "/usr/lib64/python3.4/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'str' does not support the buffer interface

libxml2 2-9-2
feedparser 5.1.3
python 3.4.3

**Comment by glu10** [comment]
This is a quick workaround that may help anyone who is still dealing with this issue:
```python
def feedparser_parse(uri):
    parsed = None
    try:
        parsed = feedparser.parse(uri)
    except TypeError:
        if 'drv_libxml2' in feedparser.PREFERRED_XML_PARSERS:
            feedparser.PREFERRED_XML_PARSERS.remove('drv_libxml2')
            parsed = feedparser.parse(uri)
    return parsed
```

On the bright side, I just tested a fresh Debian 8.3 stable installation and the problem did not appear without any workaround being used.

Versions used:
libxml2 2.9.1
feedparser 5.1.3
python 3.4.2

**Comment by brokkr** [comment]
I am getting this error after porting to Python 3. @glu10 's workaround does the trick though I must admit I don't understand the reason(ing).

OS: Fedora 23
feedparser: 5.2.1
python: 3.4.3
libxml: 2.9.3

**Comment by william20111** [comment]
This is still an issue on fedora 23. Fix above still works

**Comment by Lesik** [comment]
I am facing this issue as well. I am also running Fedora 23.

```
Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import feedparser
>>> feedparser.parse("http://www.tagesschau.de/export/video-podcast/webxl/tagesschau/");
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/feedparser.py", line 3957, in parse
    saxparser.parse(source)
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 270, in parse
    _d(reader.Name()),_d(reader.Value()))
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 70, in _d
    return _decoder(s)[0]
  File "/usr/lib64/python3.4/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'str' does not support the buffer interface
```

**Comment by sourcejedi** [comment]
It's a bug in libxml2 which should be fixed in the next release.

https://git.gnome.org/browse/libxml2/commit/python?id=65112cb36aa56bb27697c38ff52c1489cc21cba5
https://bugzilla.gnome.org/show_bug.cgi?id=758799
