### ISSUE TITLE
`io.StringIO` not working in `parse()`

### ISSUE THREAD

**Issue by murrple-1** [kurtmckee/feedparser#427]
Using version 6.0.11 and Python 3.12

The docs for `parse()` say
```
...snip...
Wrap an untrusted string in a :class:`io.StringIO` or :class:`io.BytesIO` to avoid this. Do not pass untrusted strings to this function.
...snip...
```

If you pass an `io.BytesIO`, this works fine:
```python
>>> import feedparser
>>> import io
>>> feedparser.parse(io.BytesIO(b"<rss></rss>"))
{'bozo': False, 'entries': [], 'feed': {}, 'headers': {}, 'encoding': 'utf-8', 'version': 'rss', 'namespaces': {}}
```

However, if you pass a `io.StringIO`, it crashes:
```python
>>> import feedparser
>>> import io
>>> feedparser.parse(io.StringIO("<rss></rss>"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mchristo/.local/share/virtualenvs/rss_temple-pQQQnncW/lib/python3.12/site-packages/feedparser/api.py", line 230, in parse
    data = convert_to_utf8(result['headers'], data, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mchristo/.local/share/virtualenvs/rss_temple-pQQQnncW/lib/python3.12/site-packages/feedparser/encodings.py", line 189, in convert_to_utf8
    xml_encoding_match = RE_XML_PI_ENCODING.match(tempdata)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a bytes pattern on a string-like object
```

**Comment by daaquan** [comment]
Confirmed on 6.0.14, and it fails harder than "not working": `parse()` raises an uncaught `TypeError` rather than returning a `bozo` result.

```
TypeError: cannot use a bytes pattern on a string-like object
  raised at encodings.py:189 in convert_to_utf8()
```

## Why the two inputs diverge

In 6.0.x, `_open_resource()` returns a file-like object untouched if it has `.read()`:

```python
if hasattr(url_file_stream_or_string, 'read'):
    return url_file_stream_or_string
```

but a plain `str` is encoded on the way out (`api.py:134-135`):

```python
if not isinstance(url_file_stream_or_string, bytes):
    return url_file_stream_or_string.encode('utf-8')
```

So `parse(text)` reaches `convert_to_utf8()` as `bytes`, while `parse(io.StringIO(text))` reaches it as `str` and hits a `bytes` pattern:

```python
RE_XML_PI_ENCODING = re.compile(rb'^<\?.*encoding=[\'"](.*?)[\'"].*\?>')
...
xml_encoding_match = RE_XML_PI_ENCODING.match(tempdata)   # encodings.py:189
```

The awkward part is that the `parse()` docstring at `api.py:162` recommends exactly the input that raises:

> Wrap an untrusted string in a :class:`io.StringIO` or :class:`io.BytesIO` to avoid this.

On 6.0.x, `io.BytesIO` is safe and `io.StringIO` is not, so anyone following that advice for the text case gets a crash.

## Already fixed on `main`

`main` (`a22c552`) handles all three inputs. The `_to_in_memory_file()` / `convert_file_to_utf8()` rework introduced a text path, so `io.StringIO` works there.

```
feedparser 6.0.14
  parse(text)                        entries=1 bozo=False
  parse(io.BytesIO(text.encode()))   entries=1 bozo=False
  parse(io.StringIO(text))           TypeError: cannot use a bytes pattern on a string-like object
                                     raised at encodings.py:189 in convert_to_utf8()
feedparser main (unreleased)
  parse(text)                        entries=1 bozo=False
  parse(io.BytesIO(text.encode()))   entries=1 bozo=False
  parse(io.StringIO(text))           entries=1 bozo=False
```

So this is fixed for the next major, but broken in every 6.0.x release. Two things that might still be worth doing on the maintenance branch:

1. Reword the `api.py` docstring so it does not recommend `io.StringIO` on 6.0.x, or
2. Encode text streams in `_open_resource()` so the recommendation holds.

## Workaround on 6.0.x

```python
feedparser.parse(io.BytesIO(text.encode("utf-8")))   # instead of io.StringIO(text)
```

<details>
<summary>Environment</summary>

`python:3.12-slim` (CPython 3.12.14), network-isolated container.
`feedparser==6.0.14` from PyPI; `main` installed editable at `a22c552`.

</details>
