### ISSUE TITLE
Python3: >>> import feedparser : "AttributeError: module 'feedparser.sgml' has no attribute 'charref'"

### ISSUE THREAD

**Issue by mjb-v9-5-2** [kurtmckee/feedparser#97]
```
$ git clone https://github.com/kurtmckee/feedparser.git
Cloning into 'feedparser'...
remote: Counting objects: 15554, done.
remote: Total 15554 (delta 0), reused 0 (delta 0), pack-reused 15554
Receiving objects: 100% (15554/15554), 6.08 MiB | 1.22 MiB/s, done.
Resolving deltas: 100% (9481/9481), done.
Checking connectivity... done.

$ sudo python3 setup.py install
..
..
Installed /usr/local/lib/python3.5/dist-packages/feedparser-5.2.1-py3.5.egg
..
Installed /usr/local/lib/python3.5/dist-packages/sgmllib3k-1.0.0-py3.5.egg
Finished processing dependencies for feedparser==5.2.1

$ python3

>>> import feedparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'feedparser'

>>> import sys
>>> sys.path.append('/home/python modules/feedparser')
>>> import feedparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/python modules/feedparser/feedparser/__init__.py", line 39, in <module>
    from . import api
  File "/home/python modules/feedparser/feedparser/api.py", line 53, in <module>
    from .html import _BaseHTMLProcessor
  File "/home/python modules/feedparser/feedparser/html.py", line 10, in <module>
    from .sgml import *
AttributeError: module 'feedparser.sgml' has no attribute 'charref'

```

yet:

```
$ sudo pip3 install feedparser
[sudo] password for mongo: 
..
Requirement already satisfied (use --upgrade to upgrade): feedparser in /usr/local/lib/python3.5/dist-packages/feedparser-5.2.1-py3.5.egg
Requirement already satisfied (use --upgrade to upgrade): sgmllib3k in /usr/local/lib/python3.5/dist-packages/sgmllib3k-1.0.0-py3.5.egg (from feedparser)

$ python3
>>> import feedparser
>>> dir(feedparser)
['CharacterEncodingOverride', 'CharacterEncodingUnknown', 'NonXMLContentType', 'ThingsNobodyCaresAboutButMe', 'USER_AGENT', 'UndeclaredNamespace', '__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__license__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'absolute_import', 'api', 'datetimes', 'encodings', 'exceptions', 'html', 'http', 'mixin', 'namespaces', 'parse', 'parsers', 'registerDateHandler', 'sanitizer', 'sgml', 'unicode_literals', 'urls', 'util']
```

**Comment by DueyTP** [comment]
I had this issue and fixed it my moving to the parent directory. I was in ~/git/feedparser then moved to ~/git/ and it worked.

**Comment by Bryce1010** [comment]
```
$ sudo pip3 install feedparser
The directory '/home/bryce1010/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bryce1010/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: feedparser in /usr/local/lib/python3.6/dist-packages
bryce1010@bryce1010-Lenovo-13IWL:~/Downloads/feedparser-develop$ python3
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import feedparper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'feedparper'
>>> import feedparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bryce1010/Downloads/feedparser-develop/feedparser/__init__.py", line 39, in <module>
    from . import api
  File "/home/bryce1010/Downloads/feedparser-develop/feedparser/api.py", line 53, in <module>
    from .html import _BaseHTMLProcessor
  File "/home/bryce1010/Downloads/feedparser-develop/feedparser/html.py", line 10, in <module>
    from .sgml import *
AttributeError: module 'feedparser.sgml' has no attribute 'charref'
>>> 
```
but i can't solve it!

**Comment by kurtmckee** [comment]
Hi, thanks for reporting this!

It looks like you've downloaded a copy of feedparser locally and, although you've installed it using pip3, it's getting imported from the local feedparser directory. This is clear from the directory names in the traceback exception.

Try renaming the directory in your downloads folder (or deleting it) and then try importing. Let me know the results!

**Comment by Bryce1010** [comment]
Hi, thanks for your help.
After I deleted the folder, and install it by conda ,it finally works.
@kurtmakee

**Comment by kurtmckee** [comment]
Awesome, I'm glad to hear it! =)

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
#Close
